language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer require codeception/codeception flow/jsonpath
  - wget http://robo.li/robo.phar
  - chmod +x robo.phar

script: ./robo.phar test
