language: php
php:
  - '7.2'
  - '7.3'

before_script:
  - composer req codeception/codeception flow/jsonpath squizlabs/php_codesniffer --dev
  - wget http://robo.li/robo.phar
  - chmod +x robo.phar

script:
  - composer cs
  - ./robo.phar test
